### ISSUE TITLE
Kong in Docker (via docker-compose) is maxing CPU.

### ISSUE THREAD

**Issue by paulinder** [Mashape/docker-kong#27]
Trying to set Kong up in a docker-compose environment.

Here is my `docker-compose.yml`:

```yaml
version: '2'
services:
  kong-cassandra:
    image: cassandra:2.2.4
    volumes:
      - ./cassandra:/var/lib/cassadra
    ports:
      - 9042

  kong:
    image: mashape/kong:0.7.0
    restart: always
    ports:
      - 8000:8000
      - 8001:8001
      - 8443:8443
      - 7946:7946
      - 7946:7946/udp
    links:
      - kong-cassandra:cassandra
      - lb

  lb:
    image: dockercloud/haproxy
    links:
      - serviceA
    environment:
      - DOCKER_TLS_VERIFY
      - DOCKER_HOST
      - DOCKER_CERT_PATH
    volumes:
      - $DOCKER_CERT_PATH:$DOCKER_CERT_PATH
    ports:
      - 80

  serviceA:
    extends:
      file: common.yml
      service: microservice
    build:
      context: services/serviceA/
    environment:
      - 'VIRTUAL_HOST=*/serviceA, */serviceA/*'
    command: "python main.py"
```

After starting up, the Kong container eats up more and more memory up to about 1.2 GB, and keeps both cores in the docker-machine at high usage. 

At first, I am not consistently able to GET on ports 8000 and 8001. Sometimes they are available after a fresh startup, but after a while those endpoints start timing out. I have not yet been able to set it up so that requests are passed on to the load balancer behind it.

```
CONTAINER           CPU %               MEM USAGE / LIMIT   MEM %               NET I/O               BLOCK I/O
3ccd4130717e        0.02%               19.01 MB / 2.1 GB   0.91%               21.91 kB / 8.606 kB   2.822 MB / 0 B
687d13e230bf        178.61%             1.18 GB / 2.1 GB    56.19%              15.4 kB / 17.62 kB    16.38 kB / 106.5 kB
9b4b4fce624a        0.43%               37.04 MB / 2.1 GB   1.76%               22.05 kB / 8.596 kB   4.19 MB / 0 B
bc4f15fcbd70        0.02%               24.94 MB / 2.1 GB   1.19%               103.5 kB / 60.59 kB   7.692 MB / 8.192 kB
c3774ed1f6f7        0.80%               455.5 MB / 2.1 GB   21.69%              40.34 kB / 30.6 kB    51.06 MB / 1.004 MB
e6b19df2c5cb        0.02%               23.33 MB / 2.1 GB   1.11%               22.18 kB / 8.638 kB   7.442 MB / 0 B```

Will edit as I hack away...
