### ISSUE TITLE
Cannot connect to Cassandra on startup

### ISSUE THREAD

**Issue by ghost** [Mashape/docker-kong#36]
Every time I try to start Kong, I get the following error...

> [INFO] kong 0.8.1
> [INFO] Using configuration: /etc/kong/kong.yml
> [INFO] Setting working directory to /usr/local/kong
> [INFO] database...........cassandra contact_points=kong-database:9042 data_centers= ssl=verify=false enabled=false port=9042 timeout=5000 replication_strategy=SimpleStrategy keyspace=kong replication_factor=1 consistency=ONE
> [INFO] Leaving cluster..
> [ERR] All hosts tried for query failed. kong-database:9042: connection refused for socket with peer kong-database:9042.
> [ERR] Could not start Kong

A docker ps shows the following

> a831fdfb1751        cassandra:2.2       "/docker-entrypoint.s"   53 minutes ago      Up 53 minutes       7000-7001/tcp, 7199/tcp, 9160/tcp, 0.0.0.0:9042->9042/tcp   kong-database

I've already got Cassandra running as instructed with a link named kong-database. I can shell into kong-database and run cqlsh fine.

Anyone have any idea what I can try to get closer to uncovering the problem?

**Comment by thefosk** [comment]
I can't replicate this issue.

**Comment by JakeGlascock** [comment]
I can.

**Comment by JakeGlascock** [comment]
If you're using docker compose with the docker mac beta like I am, it looks like you need to add "restart: always" to your docker compose yaml file.  Cheers!

**Comment by isanjaykp** [comment]
I am also getting same issue...appreciate any pointer ; my cassandra cluster has two nodes runs on different availabilty zone us-east-1b and us-east-1c. Cassandra listent on private ip and broadcast on public ip. I am using snitch Ec2Snitch.
====
INFO] kong 0.8.3
[INFO] Using configuration: /etc/kong/kong.yml
[INFO] Setting working directory to /usr/local/kong
[INFO] database...........cassandra contact_points=xx.xx.xx.xx:9042 data_centers= ssl=verify=false enabled=false port=9042 timeout=5000 replication_strategy=SimpleStrategy keyspace=kong replication_factor=1 consistency=ONE
[INFO] Leaving cluster..
[ERR] All hosts tried for query failed. xx.xx.xx.xx:9042: connection refused for socket with peer xx.xx.xx.xx:9042.
[ERR] Could not start Kong
===

**Comment by JakeGlascock** [comment]
The reason I was getting that error was because kong-database hadn't been started yet, so kong couldn't connect to it, therefore it exited.  I fixed this by adding "restart: always" to my docker-compose yaml file.  I'm not sure how you're setting this up exactly, but make sure that your cassandra cluster is able to be connected to.

**Comment by jgielstra** [comment]
It is a timing issue, for apps that aren't tolerant of out of order starts I add a bit of bash script
```
SERVICE=<BLAH>
echo "checking $SERVICE"
VAL=1
MAXWAIT=20
while ! nc -z $(echo -n $SERVICE | sed -e 's/:/ /') &> /dev/null; do
    sleep $VAL
    echo -n "."
                VAL=$((VAL+2))
                if [ $VAL -gt $MAXWAIT ]; then
                                echo "Waited for 20 seconds, no $SERVICE exiting"
                                exit 1
                fi
done
```

**Comment by djeeg** [comment]
I am getting the same issue

```
docker run -d --name kong-database -p 9042:9042 cassandra:2.2
docker logs -f --tail="50" kong-database
```
wait for cassandra to start
ctrl-c to kill [logs] command
```
docker run --name kong1 --link kong-database:kong-database -e "DATABASE=cassandra" --security-opt seccomp:unconfined mashape/kong
```

```
kong 0.8.3
Using configuration: /etc/kong/kong.yml
Setting working directory to /usr/local/kong
database...........cassandra contact_points=kong-database:9042 data_centers= ssl=verify=false enabled=false port=9042 timeout=5000 replication_str
Leaving cluster..
All hosts tried for query failed. kong-database:9042: timeout for socket with peer kong-database:9042.
Could not start Kong
```

**Comment by djeeg** [comment]
I couldn't get this working with docker LINK network bindings, so I have converted to docker OVERLAY network

Needed a custom kong.yml to make the Cassandra connection configurable from environmental variable
As noted here https://groups.google.com/forum/#!topic/konglayer/mfjBUwQHHHk
```
cassandra:
  contact_points:
    - "CASSANDRA_SERVICE_HOST"
```
	
And a custom setup script to regex replace the configuration with an environment variable passed from compose

```
if [ -n "$CASSANDRA_SERVICE_HOST" ]; then
  sed -ie "s/CASSANDRA_SERVICE_HOST/$CASSANDRA_SERVICE_HOST/" /etc/kong/kong.yml
fi
```
	
Those two files then needed overriding in a custom dockerfile

```
FROM mashape/kong:0.8.3
COPY config.docker/kong.yml /etc/kong/
ADD setup.sh setup.sh
RUN chmod +x setup.sh
```

Then the docker-compose to create the two look like this

```
  kong_cassandra1:
    build:
      context: ./../../docker/kong_cassandra/
      dockerfile: Dockerfile
    container_name: kong_cassandra1
    networks:
      - front-tier
    environment:
      - CASSANDRA_LISTEN_ADDRESS=kong_cassandra1
      - CASSANDRA_BROADCAST_ADDRESS=kong_cassandra1
	   
  kong1:
    build:
      context: ./../../docker/kong/
      dockerfile: Dockerfile
    networks:
      - front-tier
    environment:
      - DATABASE=cassandra
	  - CASSANDRA_SERVICE_HOST=kong_cassandra1:9042
    ports:
      - "8000:8000"
      - "8001:8001"
    security_opt:
      - seccomp:unconfined
    restart: always
```
