### ISSUE TITLE
Inconsistent cluster state when running kong cluster in docker swarm

### ISSUE THREAD

**Issue by endeepak** [Mashape/docker-kong#93]
### Problem

When running kong cluster in docker swarm, the `/cluster` API returns different number of nodes in different kong node

### Steps to reproduce

* Create a file kong.yml with content

```yml
version: '3.0'

services:
  database:
    image: postgres:9.5
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong

  kong:
    image: kong:0.9.9
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong_database # When you use docker stack deploy, service name will be <stack-name>_<service-name>
      - KONG_LOG_LEVEL=debug
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 30s
    healthcheck:
      test: curl -f http://localhost:8001/status || exit 1
      interval: 30s
      timeout: 5s
      retries: 5
```
* Start docker in swarm mode using `docker swarm init`
* Deploy the above service as docker stack using `docker stack deploy -c kong.yml kong`
* Wait for kong to start responding to `curl localhost:8001/status`
* Scale up kong nodes to 4 by running `docker service scale kong_kong=4`
* Wait for docker services replication to become 4/4. Check this by running `docker service ls`. which should produce out like this
```
ID                  NAME                MODE                REPLICAS            IMAGE               PORTS
ozga3khkmfav        kong_kong           replicated          4/4                 kong:0.9.9          *:8000->8000/tcp,*:8001->8001/tcp,*:8443->8443/tcp
tyav97i3nrz7        kong_database       replicated          1/1                 postgres:9.5        *:5432->5432/tcp
```
* Check the cluster status on each node by running `curl localhost:8001/cluster`

**Actual**
* Cluster API lists different set / different number of kong nodes in different kong node

**Expected**
* Cluster API should list same set of kong nodes in all kong nodes 

### Additional info
* Attached below GIF of watch command on `curl localhost:8001/cluster` against docker swarm load balancer which routes traffic to different kong nodes

![kong-cluster-issue](https://user-images.githubusercontent.com/310608/28766297-a420702a-75ec-11e7-933c-6619db3605e1.gif)

* docker info

```
➜  ~ docker info
Containers: 23
 Running: 5
 Paused: 0
 Stopped: 18
Images: 62
Server Version: 17.06.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 149
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: ocko88eftvs472amxzfawp8jt
 Is Manager: true
 ClusterID: m5bdatgau8j7vigtygpv2dxs6
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Root Rotation In Progress: false
 Node Address: 192.168.65.2
 Manager Addresses:
  192.168.65.2:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.36-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952GiB
Name: moby
ID: 76HL:QFBE:D3L2:WN4A:XY4W:ZDGQ:3NVD:B4CL:Z6LS:UPLJ:SJHJ:ZBIL
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 89
 Goroutines: 214
 System Time: 2017-07-31T07:05:17.598295454Z
 EventsListeners: 6
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```
